# -*- coding: utf-8 -*-
"""image processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-bUJVXBya9KMPUT9aQdrtGWMLl0n45a
"""

import cv2
import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

def extract_colors(image_path, k=7, n_init=10):
    # Load image
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Reshape image to be a list of pixels
    pixels = image.reshape((-1, 3))

    # Perform K-means clustering
    kmeans = KMeans(n_clusters=k, n_init=n_init)
    kmeans.fit(pixels)

    # Get the cluster centers (dominant colors)
    dominant_colors = kmeans.cluster_centers_.astype(int)

    return dominant_colors

def plot_colors(colors):
    # Plot the colors as a bar chart
    plt.figure(figsize=(8, 2))
    plt.bar(range(len(colors)), [1]*len(colors), color=[color/255.0 for color in colors])
    plt.axis('off')
    plt.title("Face Palettes")
    plt.show()

image_path = 'face2.webp'
dominant_colors = extract_colors(image_path, k=7, n_init=10)
plot_colors(dominant_colors)

